horiz_move_speed = 0;
vert_move_speed = 0;
grav = 0.5;
walk_speed = 6;
//grounded = false;
//gameOver = false;
//gameOverTimer = 40;
terrain = [oDirt, oDirt3, oDirtWinter]
fences = [oFence, oFenceWinter]
isRight = true;
isInvincible = false;
invincibleTimer = 30;
canDestroy = false;
canDestroyTimer = 400;
canDestroyTimerMax = canDestroyTimer;
hasBoot = false;
hasBootTimer = 400;
hasBootTimerMax = hasBootTimer;
flashActive = false; // Controls whether flickering is enabled
flashSpeed = 0;      // How often the alpha changes (e.g., every 5 steps
flashAlpha = 0;
flashColor = c_white;

timerBarWidth = 50;
timerBarHeight = 12;
timerBarX = x; //timer will be the same x coord as farmer
//timerBarGlovex = x; //timer will be the same x coord as farmer
timerBarBootY = y - 60;
timerBarGloveY = y - 30;
