horiz_move_speed = 0;
vert_move_speed = 0;
grav = 0.5;
walk_speed = 3;
grounded = false;
gameOver = false;
gameOverTimer = 40;
terrain = [oDirt, oDirt3]
isRight = true;
isInvincible = false;
invincibleTimer = 20;
canDestroy = false;
canDestroyTimer = 300;
hasBoot = false;
hasBootTimer = 300;