horiz_move_speed = 0;
vert_move_speed = 0;
grav = 0.5;
walk_speed = 6;
//grounded = false;
//gameOver = false;
//gameOverTimer = 40;
terrain = [oDirt, oDirt3]
isRight = true;
isInvincible = false;
invincibleTimer = 30;
canDestroy = false;
canDestroyTimer = 400;
hasBoot = false;
hasBootTimer = 400;
flashActive = false; // Controls whether flickering is enabled
flashSpeed = 0;      // How often the alpha changes (e.g., every 5 steps
flashAlpha = 0;
flashColor = c_white;